#!/usr/bin/env python3
"""Ensure clang-14-compatible llvm-profdata-14/llvm-cov-14 are on disk.

Why: this benchmark's `coverage` binaries are all built with clang-14 (Debian
bookworm), which emits raw llvm-profile-format version 8. A host's system
llvm-profdata/llvm-cov is very likely a newer, ABI-incompatible major version
-- it fails to merge/export the raw profile and mcp-server's `reach`
capability just silently reports not_fired (no loud error). mcp-server's
reach.go already falls back to explicitly-named llvm-profdata-14/llvm-cov-14
on $PATH if present; this script's job is only to make sure those exist.

Approach (idempotent -- skips docker entirely if the cache is already warm):
  1. If <cache-dir>/bin/llvm-profdata-14 and llvm-cov-14 already exist and are
     executable, return their paths immediately.
  2. Otherwise: spin up a throwaway container from a bookworm+clang14 image,
     `apt-get install --download-only` the llvm-14 package inside it (apt
     resolves+downloads the full dependency closure -- libllvm14, libz3-4,
     etc -- automatically, no need to hand-list them), `docker cp` the .debs
     out, `dpkg-deb -x` each one into --cache-dir without needing root.
  3. The raw extracted llvm-profdata-14/llvm-cov-14 binaries are linked
     against libLLVM-14.so, which isn't on the host's default loader path --
     so this script also writes small wrapper scripts at
     <cache-dir>/bin/llvm-profdata-14 and <cache-dir>/bin/llvm-cov-14 that set
     LD_LIBRARY_PATH to the extracted lib dir before exec'ing the real
     binaries. Those wrapper scripts, not the raw dpkg-extracted ones, are
     what a caller should put first on $PATH.
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import tempfile
import uuid
from pathlib import Path

import onboarding_lib as lib

DEFAULT_IMAGE = "debian:bookworm"

WRAPPER_TMPL = """#!/bin/sh
# Auto-generated by ensure_llvm14.py -- exec the real {name} with its
# dependency libs (libLLVM-14.so et al) on the loader path.
export LD_LIBRARY_PATH="{libdir}${{LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}}"
exec "{real_bin}" "$@"
"""


def _wrapper_paths(cache_dir: Path) -> tuple[Path, Path]:
    bindir = cache_dir / "bin"
    return bindir / "llvm-profdata-14", bindir / "llvm-cov-14"


def _already_cached(cache_dir: Path) -> bool:
    profdata, cov = _wrapper_paths(cache_dir)
    return (
        profdata.is_file() and os.access(profdata, os.X_OK)
        and cov.is_file() and os.access(cov, os.X_OK)
    )


def _find_real_bin(cache_dir: Path, name: str) -> Path | None:
    """dpkg-deb -x layout varies a bit by package version -- search for it
    rather than hardcoding a single path (usr/bin/<name> is typical, but some
    llvm-14 builds put the canonical binary under usr/lib/llvm-14/bin/ and
    usr/bin/<name> is itself a thin wrapper)."""
    candidates = sorted(cache_dir.rglob(name))
    for c in candidates:
        if c.is_file() and os.access(c, os.X_OK):
            return c
    return None


def _find_libdir(cache_dir: Path) -> Path | None:
    hits = list(cache_dir.rglob("libLLVM-14.so*"))
    if not hits:
        return None
    return hits[0].parent


def _write_wrappers(cache_dir: Path) -> dict:
    real_profdata = _find_real_bin(cache_dir, "llvm-profdata-14")
    real_cov = _find_real_bin(cache_dir, "llvm-cov-14")
    libdir = _find_libdir(cache_dir)
    if not real_profdata or not real_cov or not libdir:
        return {
            "ok": False,
            "error": f"extraction incomplete: profdata={real_profdata} cov={real_cov} libdir={libdir}",
        }
    profdata_wrapper, cov_wrapper = _wrapper_paths(cache_dir)
    profdata_wrapper.parent.mkdir(parents=True, exist_ok=True)
    profdata_wrapper.write_text(WRAPPER_TMPL.format(name="llvm-profdata-14", libdir=libdir, real_bin=real_profdata))
    cov_wrapper.write_text(WRAPPER_TMPL.format(name="llvm-cov-14", libdir=libdir, real_bin=real_cov))
    profdata_wrapper.chmod(0o755)
    cov_wrapper.chmod(0o755)
    return {"ok": True, "profdata": str(profdata_wrapper), "cov": str(cov_wrapper)}


def _docker_extract_llvm14(image: str, cache_dir: Path) -> dict:
    cname = f"fbbench-llvm14-{uuid.uuid4().hex[:10]}"
    cache_dir.mkdir(parents=True, exist_ok=True)
    try:
        r = subprocess.run(["docker", "run", "-d", "--name", cname, image, "sleep", "infinity"],
                            capture_output=True, text=True, timeout=300)
        if r.returncode != 0:
            return {"ok": False, "error": f"docker run failed: {r.stderr.strip()[-500:]}"}

        dl_cmd = (
            "apt-get update -qq && mkdir -p /tmp/debs && "
            "apt-get install -y --reinstall --download-only "
            "-o Dir::Cache::archives=/tmp/debs llvm-14"
        )
        r = subprocess.run(["docker", "exec", cname, "bash", "-c", dl_cmd],
                            capture_output=True, text=True, timeout=900)
        if r.returncode != 0:
            return {"ok": False, "error": f"apt-get download-only failed: {r.stderr.strip()[-500:]}"}

        with tempfile.TemporaryDirectory(prefix="llvm14debs-") as tmp:
            tmp_debs = Path(tmp) / "debs"
            r = subprocess.run(["docker", "cp", f"{cname}:/tmp/debs", str(tmp_debs)],
                                capture_output=True, text=True, timeout=300)
            if r.returncode != 0:
                return {"ok": False, "error": f"docker cp failed: {r.stderr.strip()[-500:]}"}

            debs = sorted(tmp_debs.glob("*.deb"))
            if not debs:
                return {"ok": False, "error": "no .debs downloaded"}
            for deb in debs:
                r = subprocess.run(["dpkg-deb", "-x", str(deb), str(cache_dir)],
                                    capture_output=True, text=True, timeout=120)
                if r.returncode != 0:
                    return {"ok": False, "error": f"dpkg-deb -x {deb.name} failed: {r.stderr.strip()[-1000:]}"}
        return {"ok": True}
    finally:
        subprocess.run(["docker", "rm", "-f", cname], capture_output=True, text=True)


def ensure_llvm14(image: str, cache_dir: Path) -> dict:
    if _already_cached(cache_dir):
        profdata, cov = _wrapper_paths(cache_dir)
        return {"cached": True, "path": str(profdata.parent), "profdata": str(profdata), "cov": str(cov)}

    if shutil.which("docker") is None:
        return {"cached": False, "error": "docker not found on PATH and no cached llvm14 tools present"}

    extracted = _docker_extract_llvm14(image, cache_dir)
    if not extracted.get("ok"):
        return {"cached": False, "error": extracted.get("error", "unknown extraction failure")}

    wrapped = _write_wrappers(cache_dir)
    if not wrapped.get("ok"):
        return {"cached": False, "error": wrapped.get("error", "unknown wrapper-generation failure")}

    return {"cached": False, "path": str(Path(wrapped["profdata"]).parent),
            "profdata": wrapped["profdata"], "cov": wrapped["cov"]}


def main():
    ap = argparse.ArgumentParser(
        description="Idempotently ensure llvm-profdata-14/llvm-cov-14 (wrapped with the right "
                    "LD_LIBRARY_PATH) exist on disk, extracting them from a bookworm+clang14 "
                    "docker image if the local cache doesn't already have them."
    )
    ap.add_argument("--image", default=DEFAULT_IMAGE,
                     help=f"bookworm-based docker image with llvm-14 available via apt (default: {DEFAULT_IMAGE})")
    ap.add_argument("--cache-dir", default=str(Path.home() / ".local" / "llvm14root"),
                     help="local extraction/cache dir (default: ~/.local/llvm14root)")
    args = ap.parse_args()

    result = ensure_llvm14(args.image, Path(args.cache_dir))
    lib.emit(result)


if __name__ == "__main__":
    main()
